# Generated by Django 5.2.8 on 2025-12-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0.0),
        ),
    ]
