# Generated by Django 5.2.8 on 2026-01-29 13:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='review',
            name='mood_intensity',
        ),
        migrations.RemoveField(
            model_name='review',
            name='primary_mood',
        ),
        migrations.CreateModel(
            name='ReviewMoodScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.mood')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_scores', to='movies.review')),
            ],
            options={
                'unique_together': {('review', 'mood')},
            },
        ),
    ]
